# Generated by Django 4.2.3 on 2023-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('room', models.PositiveIntegerField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('temperature', models.PositiveIntegerField(blank=True, null=True)),
                ('glucose', models.PositiveIntegerField(blank=True, null=True)),
                ('co2', models.PositiveIntegerField(blank=True, null=True)),
                ('o2', models.PositiveIntegerField(blank=True, null=True)),
                ('pressure', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
