# Generated by Django 4.2.3 on 2023-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currentValue', models.PositiveIntegerField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False)),
                ('optimal', models.PositiveIntegerField(blank=True, null=True)),
                ('deviceImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
